remote_theme: jekyll-theme-hacker # pages-themes/minimal@v0.2.0
title: The Yawning Chihuahua
description: '<a href="https://theyawninchihua.github.io/theyawninchihua">Home</a> | <a href="https://theyawninchihua.github.io/theyawninchihua/articles/">Articles</a> | <a href="https://theyawninchihua.github.io/theyawninchihua/whatthebeep/">#WhatTheBeep</a>'
baseurl: /theyawninchihua
url: https://theyawninchihua.github.io
markdown: kramdown

logo: /theyawninchihua.png
favicon_ico: "/assets/images/just-the-docs.png"

github:
  is_project_page: false