remote_theme: pages-themes/leap-day@v0.2.0
title: The Yawning Chihuahua
description: i like cars
baseurl: /theyawninchihua
url: https://theyawninchihua.github.io
markdown: kramdown

minima:
  logo: /theyawninchihua.png
  social_links:
    twitter: theyawninchihua
    youtube: theyawninchihua
    instagram: theyawninchihua
    github:  theyawninchihua

header_pages:
  - index.md
  - articles/index.md
  - whatthebeep/index.md